services:

  grafana:
    image: grafana/grafana
    restart: always
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    ports:
      - "3000:3000"
    volumes:
      - "./grafana:/etc/grafana/provisioning"
      - "var-lib-grafana:/var/lib/grafana"

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./postgres/init-scripts:/docker-entrypoint-initdb.d"
      - var-lib-postgresql:/var/lib/postgresql/data

volumes:
  var-lib-grafana:
  var-lib-postgresql:

