apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: postgres
    database: postgres
    jsonData:
      postgresVersion: 1200
      sslmode: 'disable'
    secureJsonData:
      password: 'postgres'

